services:
  api:
    build: ./backend
    container_name: emissor-api
    ports:
      - "3333:3333"
    environment:
      - MONGO_URI=mongodb://mongo:27017/emissor-nota
      - PORT=3333
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    command: npm run dev

  mongo:
    image: mongo:7
    container_name: mongo-emissor
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
